/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package brouser_java_fx_menu_e_submenu;

import br.com.jmary.home.Home;
import br.com.jmary.home.imagens.Imagens_Internas;
import br.com.jmary.utilidades.Exportando;
import br.com.jmary.utilidades.JOPM;
import br.com.jmary.utilidades.PopupMenu_Colar;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import brouser_java_fx.BrowserFX;

/**
 *
 * @author ana
 */
public class Browser_Java_FX_Submenu_01 extends javax.swing.JPanel {
    
    Exportando Exportando;
    PopupMenu_Colar PopupMenu_Colar;
    Home Home;
    String url = "www.google.com.br";
    BrowserFX BrowserFX;
        
    public Browser_Java_FX_Submenu_01( Home Home2 ) {
        Home = Home2;
        
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel28 = new javax.swing.JPanel();
        JPOpcao_26 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        JPOpcao_27 = new javax.swing.JPanel();
        tf_Endereco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rb_local = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rb_web_sem = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rb_web_com = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(667, 71));

        JPOpcao_26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_26.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_26MousePressed(evt);
            }
        });

        jLabel80.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("Endereço Web/Local.: ");

        javax.swing.GroupLayout JPOpcao_26Layout = new javax.swing.GroupLayout(JPOpcao_26);
        JPOpcao_26.setLayout(JPOpcao_26Layout);
        JPOpcao_26Layout.setHorizontalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        JPOpcao_26Layout.setVerticalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPOpcao_27.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_27.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_27MousePressed(evt);
            }
        });

        tf_Endereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseExited(evt);
            }
        });
        tf_Endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_EnderecoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_27Layout = new javax.swing.GroupLayout(JPOpcao_27);
        JPOpcao_27.setLayout(JPOpcao_27Layout);
        JPOpcao_27Layout.setHorizontalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_27Layout.setVerticalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_27Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/nuvem.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/sql.png"))); // NOI18N
        jLabel4.setToolTipText("Enviar Endereço de Html Local");

        rb_local.setToolTipText("Enviar Endereço de Html Local");
        rb_local.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rb_localMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/som.png"))); // NOI18N
        jLabel2.setToolTipText("Enviar Endereço de Html da Web Mais não mostrar os controles");

        rb_web_sem.setToolTipText("Enviar Endereço de Html da Web Mais não mostrar os controles");
        rb_web_sem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rb_web_semMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/16_chrome.png"))); // NOI18N
        jLabel3.setToolTipText("Enviar Endereço de Html da Web Mais mostrar os controles");

        rb_web_com.setSelected(true);
        rb_web_com.setToolTipText("Enviar Endereço de Html da Web Mais mostrar os controles");
        rb_web_com.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rb_web_comMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/html.png"))); // NOI18N
        jLabel5.setToolTipText("Setar Html puro");

        jLabel6.setText("FX");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_local)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_web_sem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_web_com))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(JPOpcao_26, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPOpcao_27, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_web_com)
                                .addComponent(jLabel3))
                            .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_web_sem)
                                .addComponent(jLabel2))
                            .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_local)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPOpcao_27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPOpcao_26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel28Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, rb_web_sem});

        jPanel28Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, rb_web_com});

        jPanel28Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, rb_local});

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/ip_conexao.png"))); // NOI18N
        jButton1.setToolTipText("Opções");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JPOpcao_26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseEntered

    private void JPOpcao_26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseExited

    private void JPOpcao_26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MousePressed

    private void tf_EnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseClicked
        try{
            PopupMenu_Colar = new PopupMenu_Colar(tf_Endereco);
        } catch( Exception e ){}
    }//GEN-LAST:event_tf_EnderecoMouseClicked

    private void tf_EnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoMouseEntered

    private void tf_EnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoMouseExited

    private void tf_EnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_EnderecoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoKeyReleased

    private void JPOpcao_27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseEntered

    private void JPOpcao_27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseExited

    private void JPOpcao_27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MousePressed

    private void rb_localMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_localMousePressed
        //rb_local.setSelected(false);
        rb_web_sem.setSelected(false);
        rb_web_com.setSelected(false);
    }//GEN-LAST:event_rb_localMousePressed

    private void rb_web_semMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_web_semMousePressed
        rb_local.setSelected(false);
        //rb_web_sem.setSelected(false);
        rb_web_com.setSelected(false);
    }//GEN-LAST:event_rb_web_semMousePressed

    private void rb_web_comMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_web_comMousePressed
        rb_local.setSelected(false);
        rb_web_sem.setSelected(false);
        //rb_web_com.setSelected(false);
    }//GEN-LAST:event_rb_web_comMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
    new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
        
        url = ""; try{ url = tf_Endereco.getText().trim(); } catch( Exception e ){} 
        
        if( rb_local.isSelected() == true ){
            
            abrir_Browser_Java_FX(false);
        }
        else if( rb_web_sem.isSelected() == true ){
            
            abrir_Browser_Java_FX(false);
        }
        else if( rb_web_com.isSelected() == true ){
            
            abrir_Browser_Java_FX(true); 
        }
        else{
            
            Class<Imagens_Internas> clazzHome = Imagens_Internas.class;
            JOPM JOptionPaneMod = new JOPM( 1, "FONTE DO ENDEREÇO NÃO INFORMADA\n"
                    + "\nFONTE: WEB/LOCAL"  
                    + "\nSELECIONE A FONTE DO ENDEREÇO NÃO INFORMADA"
                    + "\nOK Para Prosseguir"
                    ,"Class: " + this.getClass().getName(),
            new ImageIcon( clazzHome.getResource("logocangaco2.png")) ); 
        }
        
    } catch( Exception e ){} } }.start();      
    }//GEN-LAST:event_jLabel1MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
                        
        /*new Thread() {   @Override public void run() {*/ try { Thread.sleep( 1 ); 
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
                             
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                        
            //Home.adicionar_SubMenu(new Web_Marketing_Massivo_Submenu_02( Home ) );
            
            Exportando.fechar();
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

            //JPHtmlPrincipal.jSplitPaneHtmlPrincipal.setRightComponent(p);            
            //JPHtmlPrincipal.jSplitPaneHtmlPrincipal.setDividerLocation( 210 );
        } catch( Exception e ){ 
            Exportando.fechar();
            
            JOPM JOptionPaneMod = new JOPM( 2, this.getClass().getName() + ", \n"
                + e.getMessage() + "\n"
                , this.getClass().getName() 
            ); 
            
        } //} }.start();         
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPOpcao_26;
    private javax.swing.JPanel JPOpcao_27;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JRadioButton rb_local;
    private javax.swing.JRadioButton rb_web_com;
    private javax.swing.JRadioButton rb_web_sem;
    public javax.swing.JTextField tf_Endereco;
    // End of variables declaration//GEN-END:variables

    private void abrir_Browser_Java_FX(boolean sem_historico_e_sem_barra_de_pesquisa){
                        
        /*new Thread() {   @Override public void run() {*/ try { Thread.sleep( 1 ); 
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
                                                  
            JPanel p = new JPanel( new BorderLayout() );        
            
            if( url.endsWith( ".html" ) ){
                
                BrowserFX = new BrowserFX( url ); // acessar_URL_Interna
                
                p.add( BrowserFX, BorderLayout.CENTER );  
            }
            else if( url.endsWith( ".flv" ) ){
                
                BrowserFX = new BrowserFX( url,true ); // media_player
                
                p.add( BrowserFX, BorderLayout.CENTER );  
            }
            else if( sem_historico_e_sem_barra_de_pesquisa == false ){
                
                BrowserFX = new BrowserFX( url,true,true ); // acessar_URL_Externa sem histórico e sem barra de pesquisa 
                
                p.add( BrowserFX, BorderLayout.CENTER ); 
            }
            else if( sem_historico_e_sem_barra_de_pesquisa == true ){
                
                BrowserFX = new BrowserFX( url,true,true,true ); // acessar_URL_Externa com histórico e com barra de pesquisa 
                
                p.add( BrowserFX, BorderLayout.CENTER ); 
            }
                    
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                        
            Home.ControleTabs.AddTabsAoHome("Browser Java FX", "livroTp.gif", p );

            Exportando.fechar();
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

            //JPHtmlPrincipal.jSplitPaneHtmlPrincipal.setRightComponent(p);            
            //JPHtmlPrincipal.jSplitPaneHtmlPrincipal.setDividerLocation( 210 );
        } catch( Exception e ){ 
            Exportando.fechar();
            
            JOPM JOptionPaneMod = new JOPM( 2, this.getClass().getName() + ", \n"
                + e.getMessage() + "\n"
                , this.getClass().getName() 
            ); 
            
        } //} }.start();         
    }    
    
}